-- *************************** SqlDBM: Oracle ***************************
-- ************************* Generated by SqlDBM ************************


CREATE SEQUENCE dbo.Sequence_1 START WITH 3 INCREMENT BY 24 MAXVALUE 5 MINVALUE 4 CYCLE CACHE 34 NOORDER;