-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


CREATE FILE FORMAT CsvFileFormat
 TYPE = CSV
 COMPRESSION = BROTLI;
