-- ********************************** SqlDBM: Oracle *********************************
-- * Generated by SqlDBM: Git int - Oracle, v1 by alexey.alferov+standent@sqldbm.com *


-- ************************************** dbo.Supplier
CREATE TABLE dbo.Supplier
(
 SupplierId      NUMBER NOT NULL,
 CompanyName     CHAR(10) NOT NULL,
 Phone           CHAR(10) NOT NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY (SupplierId),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE (CompanyName)
);
COMMENT ON TABLE dbo.Supplier IS 'Basic information 
about Supplier';

