-- *************************** SqlDBM: Oracle ***************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** dbo.Product
CREATE TABLE dbo.Product
(
 ProductId          NUMBER NOT NULL,
 SupplierId         NUMBER NOT NULL,
 UnitPrice          NUMBER NULL,
 IsDiscontinued     FLOAT DEFAULT 0 NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY (ProductId),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE (SupplierId),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY (SupplierId) REFERENCES dbo.Supplier (SupplierId)
);
COMMENT ON TABLE dbo.Product IS 'Basic information 
about Product';
CREATE INDEX Index_4 ON dbo.Product (ProductId, SupplierId) SORT INVISIBLE UNUSABLE;
