-- *************************** SqlDBM: Oracle ***************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** dbo.OrderItem
CREATE TABLE dbo.OrderItem
(
 OrderId       NUMBER NOT NULL,
 ProductId     NUMBER NOT NULL,
 UnitPrice     NUMBER NOT NULL,
 Quantity      NUMBER NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY (OrderId, ProductId),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY (OrderId) REFERENCES dbo."Order" (OrderId),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY (ProductId) REFERENCES dbo.Product (ProductId)
);
COMMENT ON TABLE dbo.OrderItem IS 'Information about
like Price, Quantity';
